started ui types
khasanovbi/phaser3-rex-plugins-types pull request #2
Opened 2020-10-25 00:25 UTC by d3sandoval

I use the UI plugins heavily in a project of mine. I started some work on them in this branch and will continue to do so over the next couple of weeks.

Figured I'd open a PR so y'all know where I'm at with that work :)

This probably isn't ready to merge just yet.

Feel free to comment with any feedback and THANKS FOR STARTING THIS PROJECT!

2020-10-26 22:51 UTC, khasanovbi commented
Hi, thanks for your contribution a lot)

2020-10-27 01:23 UTC, khasanovbi requested changes

2020-10-27 01:23 UTC, khasanovbi commented on @types/phaser3-rex-plugins/templates/ui/ObjectFactory.d.ts
> +    register(type: string, callback: Function): void
```suggestion
    static register(type: string, callback: Function): void
```

2020-10-27 01:23 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/behaviors/textedit/TextEdit.d.ts
> +    isOpened(): boolean
`isOpened` and `text` are readonly properties, not a functions
It's should be in one of forms: `readonly isOpened: boolean` or `get isOpened(): boolean`

2020-10-27 01:23 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/behaviors/textedit/TextEdit.d.ts
> +    inputText: string
`inputText` should be instance of `InputText` class.

2020-10-27 01:23 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/behaviors/textedit/TextEdit.d.ts
> +    open(config: any, onCloseCallback: Function): this
- config should be interface with 2 optional `onClose?` and `onTextChanged?` params
- Looks like it should be 2 function overloads:
`open(config: any, onCloseCallback: Function): this`
and
`open(onCloseCallback: Function): this`
- onCloseCallback could be more specific callback that take GameObject as first param.

2020-10-27 01:23 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/behaviors/textedit/TextEdit.d.ts
> +    inputText: string
`inputText`, `onClose`, `delayCall` can be undefined, it's need to change to `inputText?`, ...

2020-10-27 01:23 UTC, khasanovbi commented on @types/phaser3-rex-plugins/templates/ui/ui-plugin.d.ts
> +  }
Сould you please add  `get viewport(): GetViewport` or TODO to add it later?

2020-10-27 01:23 UTC, khasanovbi commented on @types/phaser3-rex-plugins/templates/ui/ui-plugin.d.ts
> +    getParentSizer(gameObject: Phaser.GameObjects.GameObject): Phaser.GameObjects.GameObject
This types are reused in many places, could you create a file `plugins/gameobjects/containerlite/GetParent.d.ts` and put there
```
type GetParentFunc = (gameObject: Phaser.GameObjects.GameObject): Phaser.GameObjects.GameObject
```
Similar suggestion for other types here.

2021-02-16 00:10 UTC, atrich commented
@d3sandoval / @khasanovbi is this PR still being worked on? Would love to have access to these UI types. If this PR is not still being worked on, I could branch and work on completing the changes necessary.

2021-02-16 03:01 UTC, d3sandoval commented
@atrich I am no longer working on it. You are more than welcome to pick up where I left off

2021-02-16 19:57 UTC, khasanovbi commented
@atrich It would be great if you could help

2021-02-18 22:45 UTC, atrich commented
Ok, I have forked this PR and am working on addressing the comments so far as well as adding additional UI types that I need for the project I'm working on.

2021-02-19 00:04 UTC, atrich commented
@khasanovbi can you help me understand why this is a standalone project instead of being part of DefinitelyTyped? I'm having problems testing my changes with my main project, I can't seem to get typescript to completely read these type definition files. And it's also complaining about redefinition of phaser.d.ts types which is coming from this project's node_modules and is also included in my own project's node_modules.

2021-02-23 18:29 UTC, khasanovbi commented
@atrich could you please show your `tsconfig.json` settings?

I would be happy if this project became part of DefinitelyTyped. But I encountered some problems with it, it is not very convenient to keep everything in one file, I would like to leave the division by modules. Types in DefinitelyTyped seemed to me more suitable for libraries with a single namespace, and the `phaser3-rex-plugins` project seemed more like a set of modules. The dtsgen didn't help me much in generating it, so I decided to declare these modules manually.

2021-02-24 23:25 UTC, atrich commented
Very basic tsconfig:

```
{
    "compilerOptions": {
        "target": "es6",
        "module": "ES2015",
        "moduleResolution": "node",
        "outDir": "dist",
        "rootDir": "src",
        "allowSyntheticDefaultImports": true
    },
    "include": [
        "./src/**/*"
    ]
}
```

What I had done was to add a directory junction in my node_modules to my local clone of phaser3-rex-plugins-types and then added "node_modules/phaser3-rex-plugins-types" to my tsconfig include per readme instructions.

(It's possible I hit the issue with phaser being included twice because I'm using rollup for my deployment)

2021-02-24 23:29 UTC, atrich commented
Also, if you'd like to see my work-in-progress branch, I pushed it here: https://github.com/khasanovbi/phaser3-rex-plugins-types/compare/master...atrich:master. This should address most of your PR comments from this thread, but I'm unsure of all the style choices & I haven't been able to test fully in my project for the reasons mentioned

2021-02-26 17:35 UTC, khasanovbi commented
For development purposes you can use [npm link](https://docs.npmjs.com/cli/v7/commands/npm-link). 
```
cd ~/phaser3-rex-plugins-types/
npm link
cd ~/your-project/
npm link phaser3-rex-plugins-types
```
I didn't work with rollup but it seems to me that this is a problem at the typescript level. I'm think this should prevent including types twice.

2021-02-26 22:31 UTC, khasanovbi commented
@atrich Could you create a new PR please? It would be easier to review.

2021-03-25 02:59 UTC, khasanovbi commented
Already included in https://github.com/khasanovbi/phaser3-rex-plugins-types/pull/12

2021-03-25 02:59 UTC, closed without merging