Add some UI types
khasanovbi/phaser3-rex-plugins-types pull request #7
Opened 2021-02-26 22:41 UTC by atrich

This is a continuation of this PR: https://github.com/khasanovbi/phaser3-rex-plugins-types/pull/2

2021-02-27 10:54 UTC, khasanovbi commented
Could you rebase from master please, revert changes in `package.json`, `package-lock.json`, and call `npm run prettier`?

JFYI. I was able to reproduce the problem with two versions of phaser in my project only at development mode with npm link.

Before that, I ran the project through webpack and check types through `fork-ts-checker-webpack-plugin` and `babel-loader` and doesn't see any errors.

However, when I run directly through `tsc`, I saw errors. I don't know a good solution right now, I need time to research it. For now I will update the phaser to the latest version in `package-lock.json` to prevent type confilicts.

2021-03-01 00:49 UTC, khasanovbi requested changes
Overall looks good.

Also you can add `rexInputText` to https://github.com/khasanovbi/phaser3-rex-plugins-types/blob/master/%40types/phaser3-rex-plugins/phaser/GameObjects.d.ts#L6
to support calls like `scene.add.rexInputText(x, y, width, height, config);` and `scene.make.rexInputText` and update `Input text` checkbox at README.

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/gameobjects/dom/InputText.d.ts
> +declare module 'phaser3-rex-plugins/plugins/gameobjects/dom/InputText' {
file path and module name should include `inputtext` `phaser3-rex-plugins/plugins/gameobjects/dom/inputtext/InputText`

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/templates/ui/ui-plugin.d.ts
> +        get viewport(): typeof GetViewport;
Should be `Phaser.Geom.Rectangle` or `ReturnType<typeof GetViewport>`

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/utils/promise/WaitEvent.d.ts
> +    export type WaitEvent = (
Let's keep functions here instead of types

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/utils/system/GetViewport.d.ts
> +        out: undefined | boolean | Phaser.Geom.Rectangle,
Maybe simplify this `out?: boolean | Phaser.Geom.Rectangle`

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/templates/ui/ObjectFactory.d.ts
> +        constructor(scene: Phaser.Scene);
`scene`, `displayList`, `updateList` params
`destroy(): void;`

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/utils/input/IsPointerInBounds.d.ts
> +        preTest: TestFunc,
It's look like `preTest?: TestFunc` and `postTest?: TestFunc` are optional params

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/utils/promise/WaitEvent.d.ts
> +    ) => Promise<(resolve: Function, reject: Function) => {}>;
`Promise<void>`

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/utils/promise/WaitEvent.d.ts
> +    ) => Promise<(resolve: Function, reject: Function) => {}>;
`Promise<void>`

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/gameobjects/containerlite/GetParent.d.ts
> +    export function GetParent(gameObject: Phaser.GameObjects.GameObject): Phaser.GameObjects.GameObject;
Return type should be in both functions `Phaser.GameObjects.GameObject | undefined`

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/templates/ui/ui-plugin.d.ts
> +        getParentSizer: typeof GetParentSizer;
Lets describe this methods in separate interface:
```
interface methods {
    ...
}

export default class UIPlugin extends Phaser.Plugins.ScenePlugin implements methods {
}
```

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/templates/ui/ui-plugin.d.ts
> +        setChildrenInteractive(gameObject: Phaser.GameObjects.GameObject, config: any): Phaser.GameObjects.GameObject; // todo replace config with real type: https://rexrainbow.github.io/phaser3-rex-
Let's move this function definition to separate file `ui/utils/setchildreninteractive/SetChildrenInteractive.d.ts`

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/gameobjects/dom/InputText.d.ts
> +    export default class InputText extends Phaser.GameObjects.DOMElement {
https://github.com/rexrainbow/phaser3-rex-notes/blob/master/plugins/gameobjects/dom/inputtext/InputText.js#L223

Same suggestion `implements methods {` like in a `templates/ui/ui-plugin`

`Resize` returns `this`, and we can't just write `typeof Resize`, so I'm suggest to create type `ResizeType` 

Something analogical I did here:

https://github.com/khasanovbi/phaser3-rex-plugins-types/blob/master/%40types/phaser3-rex-plugins/plugins/board/board/chess/RemoveAllChess.d.ts

https://github.com/khasanovbi/phaser3-rex-plugins-types/blob/master/%40types/phaser3-rex-plugins/plugins/board/board/LogicMethods.d.ts#L136

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/templates/ui/ui-plugin.d.ts
> +    import {WaitEvent, WaitComplete} from 'phaser3-rex-plugins/plugins/utils/promise/WaitEvent';
Please, don't import them directly. Let's create a file `templates/ui/utils/WaitEvent.d.ts` and import them form this file.

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/gameobjects/dom/InputText.d.ts
> +        setReadOnly(value: boolean): this;
`value?: boolean`

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/gameobjects/dom/InputText.d.ts
> +        setEnabled(enabled: boolean): this;
`enabled?: boolean`

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/gameobjects/dom/InputText.d.ts
> +        constructor(scene: Phaser.Scene, x: number, y: number, width: number, height: number, config?: any);
Looks like constructor has some overrides when x - config, width - config

2021-03-01 00:49 UTC, khasanovbi commented on @types/phaser3-rex-plugins/plugins/behaviors/textedit/TextEdit.d.ts
> +    export interface OnTextEditClosed {
Maybe better to rename this type to `OnCloseCallback` and simplify like this `type OnCloseCallback = (obj: Phaser.GameObjects.GameObject) => void;`

2021-03-07 16:05 UTC, khasanovbi commented
Hi @atrich, do you need help with PR? I could add the fixes in a separate branch.

2021-03-17 21:48 UTC, atrich commented
My apologies, @khasanovbi, due to time constraints, I've had to jettison my plans to utilize the rex plugins for my phaser project due to other incompatibilities. I am willing to respond to your issues with the PR but it may take me a while to get around to it. I'm fine if you want to add your proposed fixes in another branch.

2021-03-25 02:58 UTC, merged

2021-03-25 03:08 UTC, khasanovbi commented
Thanks for your contribution